
name: Bandit scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run bandit
        run: |
          # run recursively and produce a json report for artifacts
          bandit -r . -f json -o bandit-output.json || true

      - name: Upload bandit JSON report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-output.json
